<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>marshc</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="src/Driver/Options.fs"/>
    <Compile Include="src/Frontend/Token.fs"/>
    <Compile Include="src/Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Argu" Version="6.2.5" />
  </ItemGroup>

</Project>
